apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: nginx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k10-nfs
  resources:
    requests:
      storage: 5Gi
